name: PortalStick
main: com.matejdro.bukkit.portalstick.PortalStick
version: ${project.version} commit ${git.commit.id.abbrev}
authors: [matejdro, oliverw92, V10lator]
softdepend: [WorldGuard]
api-version: '1.13'
commands:
  portalstick:
    description: Aperture Science Portal Stick
    aliases: portal
    usage: /<command> help
permissions:
  portalstick.placeportal:
    description: Place portals
    default: true
  portalstick.teleport:
    description: Use portals
    default: true
  portalstick.admin.deleteall:
    description: Delete all
    default: op
  portalstick.language:
    description: Change language
    default: op
